package inz.project.models;

public enum Country {

	Afganistan("Afganistan"), 
	Albania("Albania"), 
	Algieria("Algieria"), 
	Andora("Andora"),
	Angola("Angola"),
	Anguilla("Anguilla"),
	Antarktyda("Antarktyda"), 
	AntiguaiBarbuda("Antigua i Barbuda"), 
	ArabiaSaudyjska("Arabia Saudyjska"), 
	Argentyna("Argentyna"),
	Armenia("Armenia"),
	Aruba("Aruba"),
	Australia("Australia"),
	Austria("Austria"),
	Azerbejdzan("Azerbejdżan"),
	Bahamy("Bahamy"),
	Bahrajn("Bahrajn"),
	Bangladesz("Bangladesz"),
	Barbados("Barbados"),
	Belgia("Belgia"),
	Belize("Belize"),
	Benin("Benin"),
	Bermudy("Bermudy"),
	Bhutan("Bhutan"),
	Białorus("Białoruś"),
	Boliwia("Boliwia"),
	BosniaiHercegowina("Bośnia i Hercegowina"),
	Botswana("Botswana"),
	Brazylia("Brazylia"),
	BruneiDarussalam("Brunei Darussalam"),
	Bulgaria("Bułgaria"),
	BurkinaFaso("Burkina Faso"),
	Burundi("Burundi"),
	Ceuta("Ceuta"),
	Chile("Chile"),
	Chiny("Chiny"),
	Curacao ("Curaçao"),
	Chorwacja("Chorwacja"),
	Cypr("Cypr"),Czad("Czad"),
	Czarnogora("Czarnogóra"),
	Dania("Dania"),
	Dominika("Dominika"),
	Dominikana("Dominikana"),
	Dzibuti("Dżibuti"),
	Egipt("Egipt"),Ekwador("Ekwador"),Erytrea("Erytrea"),
	Estonia("Estonia"),Etiopia("Etiopia"),Falklandy("Falklandy"),FidziRepublika("Fidżi Republika"),
	Filipiny("Filipiny"),Finlandia("Finlandia"),
	Francja("Francja"),Gabon("Gabon"),Gambia("Gambia"),
	Ghana("Ghana"),Gibraltar("Gibraltar"),Grecja("Grecja"),Grenada("Grenada"),
	Grenlandia("Grenlandia"),Gruzja("Gruzja"),
	Guam("Guam"),Gujana("Gujana"),Gwatemala("Gwatemala"),Gwinea("Gwinea"),
	GwineaRownikowa("Gwinea Równikowa"),GwineaBissau("Gwinea-Bissau"),Haiti("Haiti"),
	Hiszpania("Hiszpania"),Honduras("Honduras"),Hongkong("Hongkong"),Indie("Indie"),
	Indonezja("Indonezja"),Irak("Irak"),Iran("Iran"),
	Irlandia("Irlandia"),Islandia("Islandia"),Izrael("Izrael"),Jamajka("Jamajka"),
	Japonia("Japonia"),Jemen("Jemen"),Jordania("Jordania"),Kajmany("Kajmany"),
	Kambodza("Kambodża"),Kamerun("Kamerun"),Kanada("Kanada"),Katar("Katar"),Kazachstan("Kazachstan")
	,Kenia("Kenia"),Kirgistan("Kirgistan"),Kiribati("Kiribati"),Kolumbia("Kolumbia"),
	Komory("Komory"),Kongo("Kongo"), KoreanskaRepublika("Koreańska Republika"),
	Kosowo("Kosowo"),Kostaryka("Kostaryka"),Kuba("Kuba"),Kuwejt("Kuwejt"),
	Laos("Laos"),Lesotho("Lesotho"),
	Liban("Liban"),Liberia("Liberia"),Libia("Libia"),Liechtenstein("Liechtenstein"),
	Litwa("Litwa"),Luksemburg("Luksemburg"),Lotwa("Łotwa"),
	Macedonia("Macedonia"),Madagaskar("Madagaskar"),Majotta("Majotta"),
	Makau("Makau"),Malawi("Malawi"),Malediwy("Malediwy"),
	Malezja("Malezja"),Mali("Mali"),Malta("Malta"),MarianyPółnocne("Mariany Północne"),
	Maroko("Maroko"),Mauretania("Mauretania"),Mauritius("Mauritius"),
	Meksyk("Meksyk"),Melilla("Melilla"),Mikronezja("Mikronezja"),
	Minor("Minor"),
	Moldawia("Mołdawia"),Mongolia("Mongolia"),
	Montserrat("Montserrat"),Mozambik("Mozambik"),
	Myanmar("Myanmar"),Namibia("Namibia"),
	Nauru("Nauru"),Nepal("Nepal"),
	Niderlandy("Niderlandy"),Niemcy("Niemcy"),
	Niger("Niger"),
	Nigeria("Nigeria"),Nikaragua("Nikaragua"),
	Niue("Niue"),Norfolk("Norfolk"),
	Norwegia("Norwegia"),NowaKaledonia("Nowa Kaledonia"),
	NowaZelandia("Nowa Zelandia"),Oman("Oman"),
	Pakistan("Pakistan"),Palau("Palau"),
	Panama("Panama"),PapuaNowaGwinea("Papua Nowa Gwinea"),
	Paragwaj("Paragwaj"),Peru("Peru"),
	Pitcairn("Pitcairn"),PolinezjaFrancuska("Polinezja Francuska"),
	Portugalia("Portugalia"),RepublikaCzeska("Republika Czeska"),
	RepublikaKorei("Republika Korei"),RepPoludAfryki("Rep.Połud.Afryki"),
	RepSrodkowoafrykanska("Rep.Środkowoafryańska"),Rosja("Rosja"),
	Rwanda("Rwanda"),SaharaZachodnia("Sahara Zachodnia"),
	SaintBarthelemy("Saint Barthelemy"),Rumunia("Rumunia"),
	Salwador("Salwador"),Samoa("Samoa"),SamoaAmerykanskie("Samoa Amerykańskie"),
	SanMarino("San Marino"),Senegal("Senegal"),
	Serbia("Serbia"),Seszele("Seszele"),SierraLeone("Sierra Leone"),
	Singapur("Singapur"),Suazi("Suazi"),
	Slowacja("Słowacja"),Slowenia("Słowenia"),
	Somalia("Somalia"),SriLanka("Sri Lanka"),StPierreiMiquelon("St. Pierre i Miquelon"),
	StKittsiNevis("St.Kitts i Nevis"),StLucia("St.Lucia"),
	StVincentiGrenadyny("St.Vincent i Grenadyny"),StanyZjednAmeryki("Stany Zjedn. Ameryki"),
	Sudan("Sudan"),SudanPołudniowy("Sudan Południowy"),
	Surinam("Surinam"),Syria("Syria"),
	Szwajcaria("Szwajcaria"),Szwecja("Szwecja"),
	ŚwietaHelena("Święta Helena"),Tadzykistan("Tadżykistan"),
	Tajlandia("Tajlandia"),Tajwan("Tajwan"),Tanzania("Tanzania"),
	Togo("Togo"),Tokelau("Tokelau"),Tonga("Tonga"),
	TrynidadiTobago("Trynidad i Tobago"),Tunezja("Tunezja"),
	Turcja("Turcja"),Turkmenistan("Turkmenistan"),
	WyspyTurksiCaicos("Wyspy Turks i Caicos"),Tuvalu("Tuvalu"),Uganda("Uganda"),
	Ukraina("Ukraina"),Urugwaj("Urugwaj"),
	Uzbekistan("Uzbekistan"),Vanuatu("Vanuatu"),
	WallisiFutuna("Wallis i Futuna"),Watykan("Watykan"),
	Wenezuela("Wenezuela"),Wegry("Węgry"),
	WielkaBrytania("Wielka Brytania"),Wietnam("Wietnam"),Wlochy("Włochy"),
	WschodniTimor("Wschodni Timor"),WybKosciSloniowej("Wyb.Kości Słoniowej"),
	WyspaBouveta("Wyspa Bouveta"),WyspaBozegoNarodzenia("Wyspa Bożego Narodzenia"),
	WyspyCooka("Wyspy Cooka"),WyspyDziewiczeUSA("Wyspy Dziewicze-USA"),
	WyspyDziewiczeWB("Wyspy Dziewicze-W.B"),WyspyHeardiMcDonald("Wyspy Heard i McDonald"),
	WyspyKokosowe("Wyspy Kokosowe"),WyspyOwcze("Wyspy Owcze"),
	WyspyMarshalla("Wyspy Marshalla"),WyspySalomona("Wyspy Salomona"),
	WyspaSintMaarten("Wyspa Sint Maarten"),WyspySwTomaszaiKsiazeca("Wyspy Św.Tomasza i Książęca"),
	Zambia("Zambia"),ZielonyPrzyladek("Zielony Przylądek"),Zimbabwe("Zimbabwe"),
	ZjednEmiratyArabskie("Zjedn.Emiraty Arabskie");
	
	
	
	
	String name;

	Country(){}
	Country(String name) {
		this.name = name;
	}
}
